from . import register_invoice_freight
from . import crm_lead_to_opportunity1
from . import container_duplicate
from . import create_rfq_wizard
from . import create_transport_wizard
from . import create_clearance_wizard
from . import purchase_lead
from . import quotation
from . import quotation_lead
from . import purchase
from . import freight_report
