# -*- coding: utf-8 -*-
{
    'name': 'Shipment Order Management',
    'version': '1.0',
    'summary': 'Manage shipment orders',
    'author': 'Banan',
    'depends': ['base','sale','freight','account','base_accounting_kit','price_list','project','sale_management','report_xlsx'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/ir_sequence_data.xml',
        'data/crm_stage.xml',
        'wizard/payment_wizerd.xml',
        'wizard/oppreation_transfer_wizard_view.xml',
        'wizard/delivered_issues_wizard.xml',
        'wizard/daily_route_view_wizard.xml',
        'wizard/awb_views.xml.xml',
        'wizard/purchase_awb_views.xml',
        'wizard/operation_assign_wizard_view.xml',
        'wizard/operation_assign_delivered_view.xml',
        'wizard/operation_delivered_wizard_view.xml',
        'views/shipment_order_views.xml',
        'views/complaint_type.xml',
        'views/country_view_inhrited.xml',
        'views/crm_leads.xml',
        'views/freight_operation_inhert.xml',
        'views/freight_stage.xml',
        'views/online_payment_view.xml',
        'views/online_payment_config_view.xml',
        'views/shipment_order_payment_view.xml',
        'views/daily_route_view.xml',
        'views/daily_route_log_view.xml',
        'report/payment_report.xml',
        'report/sale_order_report.xml',
    ],
    'assets': {
       'web.assets_backend': [
            'shipment_order/static/src/xml/tree.xml',
            'shipment_order/static/src/js/tree_buttons.js',
       ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
