from . import freight
from . import account_move
from . import airline
from . import hr_expense
from . import package
from . import port
from . import res_partner
from . import shipment_stage
from . import trucker
from . import vessel
from . import rate_price
from . import console_operation
from . import container
from . import freight_transit
from . import crm_lead
from . import crm_config
from . import stage
from . import cals
from . import cal_purpose
from . import cal_result
from . import visit
from . import res_users
from . import purchase_order
from . import freight_manifest
from . import freight_way_bill
from . import way_bill
from . import freight_shipment
from . import road_way_bill

