from . import payment_wizard
from . import oppreaton_transfer_wizard
from . import delivered_issue_wizard
from . import daily_route_wizard
from . import awb_wizard
from . import purchase_awb_wizard
from . import operation_assign_wizard
from . import operation_assign_delivered_wizard
from . import operation_delivered_wizard